# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u21ejlCe3SgPioaqNLJ7MuLr3nxTQVEP
"""

!pip install cbpro

import cbpro
print(cbpro)

public_client = cbpro.PublicClient()
print(public_client)

public_client.get_products()

public_client.get_product_ticker(product_id="DOGE-USD")

history_data = public_client.get_product_historic_rates("DOGE-USD")
history_data

import pandas 
coin_columns = ["Date", "Open", "High", "Low", "Close"] 
for row in history_data: 
  del row [5:] 
dataframe = pandas.DataFrame(history_data, 
                            columns = coin_columns)

print(dataframe)

dataframe["5-Day Moving Averge"] = dataframe.Close.rolling(5).mean()
print(dataframe)

!pip install bta-lib
import btalib

simple_moving_averega = btalib.sma(dataframe.Close)
print(simple_moving_averega.df)

dataframe["Simple Moving Average"] = btalib.sma(dataframe.Close, period=10).df
print(dataframe)